### ISSUE TITLE
请问装备的类型是根据哪个参数确定的呢？

### ISSUE THREAD

**Issue by SymphonyIceAttack** [RedBeanN/HSoD2OpenAPI#1]
为什么只有武器是有baseType的，但是使魔，徽章，服装没有字段属性标识呢？

**Comment by RedBeanN** [comment]
之前的判断逻辑是这样的

- 有`baseType`字段为武器
- 否则有`ultraSkill`字段为使魔
- 否则有`hpBase`字段为服装
- 否则为徽章

后面会补上`type`字段标记类型

**Comment by SymphonyIceAttack** [comment]
非常感谢回复，我最近在开发一个崩坏学园装备分享码的项目。这个type字段真的很重要，而且我还发现hpBase不仅在服装的装备上出现了，有的装备对象的hpBase是0但是其实不是服装。

**Comment by SymphonyIceAttack** [comment]
> 之前的判断逻辑是这样的
> 
> * 有`baseType`字段为武器
> * 否则有`ultraSkill`字段为使魔
> * 否则有`hpBase`字段为服装
> * 否则为徽章
> 
> 后面会补上`type`字段标记类型

非常感谢回复，我最近在开发一个崩坏学园装备分享码的项目。这个type字段真的很重要，而且我还发现hpBase不仅在服装的装备上出现了，有的装备对象的hpBase是0但是其实不是服装。

**Comment by SymphonyIceAttack** [comment]
现在type字段已经有了，可以关闭这个issue了
weapon 武器
costume 服装
pet 宠物
passiveSkill 徽章
